### ISSUE TITLE
Backlog do Produto

### ISSUE THREAD

**Issue by SQLutions-FATEC** [SQLutions-FATEC/API-2-Semestre#10]
## Problema
Não sabemos exatamente o projeto como um todo, precisamos ver com o cliente quais são as partes importantes e funcionalidades que ele deseja, bem como a prioridade de cada uma das features, para o caso de não conseguirmos entregar tudo

## Proposta de solução
Montar o backlog do produto (pode se basear no do primeiro semestre) junto com o cliente. Lembrando que o mais importante é a opinião dele, mas sempre se perguntando se faz sentido o que ele diz
Quem pegar o card preenche aqui detalhes mais técnicos

## Como testar
Ler e avaliar clareza e assertividade do backlog.

**Comment by augustopiatto** [comment]
O card é do davi, mas estou mexendo por ele pois está no celular. Conseguimos terminar o backlog de produto e user stories, qualquer ajuste nestes tópicos serão melhorias, e não fazem parte deste card
