### ISSUE TITLE
Identificar se usuário é professor ou aluno

### ISSUE THREAD

**Issue by augustopiatto** [SQLutions-FATEC/API-2-Semestre#30]
## Problema
Devemos ser capaz de identificar se o usuário é um professor ou aluno, para que fluxos adequados sejam exibidos para ele.
O login não será feito de forma definitiva nesta sprint, mas podemos fazer algo temporário para conseguir acessar esses 2 fluxos.

## Proposta de solução
São sugestões, se pensar em alguma forma melhor, validar com PO e podemos seguir:
- Colocar um botão no front pra decidir qual fluxo seguir: professor ou aluno
- Fazer um input que peça e-mail, e podemos ter um e-mail para professor no banco, e um para aluno
- Acessar uma porta especifica do endpoint será identificado como professor, e outra porta, como aluno

Quem pegar o card preencher com mais informações

## **Fluxo de Execução**

**Criação do layout de login:**

- *Criação do layout de login utilizando SceneBuilder*

O layout da tela de login será desenhado conforme o wireframe. Usaremos SceneBuilder para posicionar os campos de "Usuário" e "Senha", além de dois botões que permitirão escolher o fluxo (professor ou aluno).
Um botão será adicionado abaixo do formulário de login para selecionar se o usuário é Professor ou Aluno. Ao clicar nesse botão, o sistema saberá qual fluxo seguir.
O campo de email será mantido para simular o login e fazer a verificação se é um professor ou aluno (de forma temporária nessa sprint).

**Lógica do Frontend:**
- *Javafx (backend para a interface gráfica)*

O código em Javafx irá controlar as interações da interface. Quando o usuário inserir o e-mail e clicar no botão correspondente, uma função será chamada para verificar a categoria (professor ou aluno).
Vamos simular o login ao verificar o email. O sistema identificará se o e-mail inserido é de um professor ou aluno a partir de uma lista de usuários simulada no backend.
Dependendo do botão clicado, o fluxo seguirá para a tela de Professor ou Aluno.

**Integração com o Backend:**
- *IntelliJ (para escrever o código backend em Java)* 

Como o login não será feito de forma definitiva, criaremos um endpoint simples para diferenciar o fluxo de acesso.

- **Endpoint para Professor:** será acessado por uma porta específica (por exemplo, localhost:8081).

- **Endpoint para Aluno:** será acessado por outra porta (por exemplo, localhost:8082).

O backend poderá verificar temporariamente se o usuário é professor ou aluno com base no email. Um email específico será cadastrado como "professor" e outro como "aluno" no backend.

**Simulação de Banco de Dados (temporária):**

Nesta sprint, o banco de dados será simulado no backend em Java. Teremos uma lista de emails:

Um email cadastrado como professor (ex.: professor@fatec.sp.gov.br).
Um email cadastrado como aluno (ex.: aluno@fatec.sp.gov.br).

Ao realizar o login, o sistema verifica o e-mail digitado com os cadastrados nessa lista. Isso será temporário, para simular o comportamento desejado.

**Navegação entre os fluxos:**

Após a verificação do e-mail e a escolha do botão de fluxo, o usuário será redirecionado para a tela correspondente:

- **Fluxo do Professor:** uma tela específica para o professor será exibida.

- **Fluxo do Aluno:** uma tela específica para o aluno será exibida.

A navegação será controlada através das funções em JavaFX.

## Como testar
Quem pegar o card preenche aqui

- **Testes e Validação:**
Para validar a implementação, realizaremos testes simulando o acesso de um professor e de um aluno, garantindo que os fluxos corretos sejam acionados conforme o wireframe e requisitos.
Isso permitirá visualizar o fluxo temporário de login e escolha de usuário.

**Comment by GloBrito** [comment]
Fluxo pode sofrer alterações
