### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by SQLutions-FATEC** [SQLutions-FATEC/API-2-Semestre#8]
OBS: Este card depende do #10 

## Problema
User Stories é um critério da API. Precisamos validar com o cliente se entendemos o propósito do produto que iremos criar e se nossa ideia está no caminho correto

## Proposta de solução
Criação de  User Stories e validação com o cliente

https://github.com/SQLutions-FATEC/API-2-Semestre?tab=readme-ov-file#user-stories

## Como testar
Verificar o User Stories e validar se bate com o proposto pelo Backlog de Produto

**Comment by augustopiatto** [comment]
Terminamos o backlog de produto, mas ainda temos algumas validações pendentes para o user stories.
A maior parte está completa, e portanto as tarefas que dependem dele podem avançar
